# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: SharedVariables
  - name: buidno

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'tudordumitriu/azapi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- powershell: echo "##vso[task.setvariable variable=buidno;isOutput=true]$(Build.BuildId)"
  name: setvarStep
- script: echo $(buidno)
  name: echovar

# - publish: $(System.DefaultWorkingDirectory)/AZEApi/deployment.az.api.yaml
#   artifact: deployment.az.api.yaml