# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: SharedVariables 

steps:
# - bash: echo $(Build.BuildId)
#   name: echovar
# - task: Docker@2
#   inputs:
#     containerRegistry: 'Docker Hub'
#     repository: 'tudordumitriu/azapi'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: '(Get-Content .\buildnotemplate.txt).replace(''{version}'', $(Build.BuildId)) | Set-Content .\buildno.txt'
    
# - publish: $(System.DefaultWorkingDirectory)/buildno.txt
#   artifact: buildno.txt
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "##vso[task.setvariable variable=buildno]$(Build.BuildId)"'

- bash: echo $(buildno)
  name: echovar2
# - publish: $(System.DefaultWorkingDirectory)/AZEApi/deployment.az.api.yaml
#   artifact: deployment.az.api.yaml