# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildno: '1'

steps:
- bash: echo $(Build.BuildId)
  name: echovar1
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "##vso[task.setvariable variable=buildno]$(Build.BuildId)"'
- bash: echo $(buildno)
  name: echovar2
# - publish: $(System.DefaultWorkingDirectory)/AZEApi/deployment.az.api.yaml
#   artifact: deployment.az.api.yaml