# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildno: '1'

steps:
- bash: echo $(Build.BuildId)
  name: echovar1
- bash: 'echo ##vso[task.setvariable variable=buildno;]testvalue'
  name: setvarStep
- bash: echo $(buildno)
  name: echovar

# - publish: $(System.DefaultWorkingDirectory)/AZEApi/deployment.az.api.yaml
#   artifact: deployment.az.api.yaml