apiVersion: apps/v1
kind: Deployment
metadata:
  name: azapi
  labels:
    app: azapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azapi
  template:
    metadata:
      labels:
        app: azapi
    spec:
      containers:
      - name: azapi
        image: tudordumitriu/azapi:13
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name : azapi  
spec:
  selector:
    app: azapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30643
  type: LoadBalancer
