apiVersion: apps/v1
kind: Deployment
metadata:
  name: azapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azapi
  template:
    metadata:
      labels:
        app: azapi
    spec:
      containers:
      - name: azapi
        image: tudordumitriu/azapi:l3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
            httpGet:
              path: /api/values
              port: 3002
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: v1
kind: Service
metadata:
  name : azapi  
spec:
  selector:
    app: azapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30643
  type: NodePort
